apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbotapi
  labels:
    app: chatbotapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbotapi
  template:
    metadata:
      labels:
        app: chatbotapi
    spec:
      containers:
        - name: chatbotapi
          image: 860602188711.dkr.ecr.ap-south-1.amazonaws.com/testcicdgithubactions:GPN-CICD-Test-main
          imagePullPolicy: Always
          ports:
            - containerPort: 8080