name: Deploy to EKS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: 'v1.24.0' # default is latest stable
      id: install

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.SECRET_KEY }}
        aws-region: ${{ secrets.REGION }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: testcicdgithubactions
        REPO_NAME: ${{ github.event.repository.name }}
        BRANCH_NAME: ${{ github.ref_name }}
        IMAGE_TAG: ${{ github.event.repository.name }}-${{ github.ref_name }}
      run: |
        echo "Image Tag: $IMAGE_TAG"
        echo "Repo Name: $REPO_NAME"
        echo "Branch Name: $BRANCH_NAME"
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        echo "Image: $REGISTRY/$REPOSITORY:$IMAGE_TAG"
    - name: Update kube config
      run: |
        echo aws configure list
        aws eks update-kubeconfig --name gpn-chatbot-cluster
  
    - name: Deploy to EKS
      run: |
        kubectl create namespace gpn-chatbot
        kubectl apply -n gpn-chatbot -f deployment.yaml
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml